spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: secret
            redirect-uri: "http://localhost:6543/api/auths/oauth2/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - birthday
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: secret
  client-id : secret
